import { Router, type IRouter } from "express";
import { User, ProfileEffect, type IProfileEffect } from "@workspace/db";
import { requireAuth, optionalAuth, type AuthRequest } from "../lib/auth";
import { logger } from "../lib/logger";

const router: IRouter = Router();

// ── DEFAULT EFFECTS CATALOG SEED DATA ─────────────────────────────────────────
export const INITIAL_EFFECTS = [
  {
    effectId: "emerald-aurora",
    name: "Emerald Aurora",
    nameAr: "الشفق الزمردي",
    description: "WhiterChat's signature sovereign green celestial aurora borealis undulating with atmospheric emerald plasma particles and soft luminous mist.",
    descriptionAr: "شفق سيادي زمردي أخضر يتماوج بسلاسة وانسيابية مع جزيئات بلازما مضيئة وضباب ضوئي ساحر يعكس هوية WhiterChat.",
    category: "aurora",
    rarity: "legendary",
    badge: "Signature",
    badgeAr: "العلامة الفارقة",
    colors: {
      primary: "#10b981",
      secondary: "#059669",
      accent: "#34d399",
      glow: "rgba(52, 211, 153, 0.4)",
      particles: "#6ee7b7",
      overlay: "rgba(6, 78, 59, 0.25)",
    },
    animationType: "wave",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 1,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "cyber-pulse",
    name: "Cyber Pulse",
    nameAr: "النبض الرقمي",
    description: "Deep cyan tactical telemetry grid with oscillating matrix conduits, digital horizon scanlines, and roaming telemetry beacons.",
    descriptionAr: "شبكة قياس عن بُعد تكتيكية سيانية عميقة مع قنوات مصفوفة متذبذبة وخطوط مسح رقمية دقيقة تمنح طابع السايبر الاحترافي.",
    category: "cyber",
    rarity: "epic",
    badge: "Tactical",
    badgeAr: "تكتيكي سايبر",
    colors: {
      primary: "#06b6d4",
      secondary: "#0284c7",
      accent: "#38bdf8",
      glow: "rgba(14, 165, 233, 0.35)",
      particles: "#7dd3fc",
      overlay: "rgba(8, 47, 73, 0.25)",
    },
    animationType: "scanline",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 2,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "cosmic-orbit",
    name: "Cosmic Orbit",
    nameAr: "المدار الكوني",
    description: "Deep interstellar nebula with sweeping celestial orbital rings, twinkling star clusters, and cosmic stellar dust.",
    descriptionAr: "سديم فضائي عميق مع حلقات مدارية سماوية متحركة وعناقيد نجمية متلألئة وغبار كوني عالي الدقة.",
    category: "cosmic",
    rarity: "legendary",
    badge: "Celestial",
    badgeAr: "مداري كوني",
    colors: {
      primary: "#6366f1",
      secondary: "#4338ca",
      accent: "#818cf8",
      glow: "rgba(99, 102, 241, 0.35)",
      particles: "#c7d2fe",
      overlay: "rgba(30, 27, 75, 0.3)",
    },
    animationType: "orbit",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 3,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "holographic-atmosphere",
    name: "Prism Hologram",
    nameAr: "الهولوغرام المنشوري",
    description: "Prismatic refractive spectrum field projecting iridescent chromatic dispersion waves and dynamic holographic light sweeps.",
    descriptionAr: "حقل انكسار لوني منشوري يعكس موجات طيفية قزحية ولمسات ضوئية هولوغرافية متغيرة الزوايا.",
    category: "holographic",
    rarity: "epic",
    badge: "Iridescent",
    badgeAr: "قزحي مشع",
    colors: {
      primary: "#ec4899",
      secondary: "#8b5cf6",
      accent: "#f472b6",
      glow: "rgba(236, 72, 153, 0.35)",
      particles: "#ddd6fe",
      overlay: "rgba(88, 28, 135, 0.25)",
    },
    animationType: "shimmer",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 4,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "black-chrome",
    name: "Black Chrome",
    nameAr: "الكروم الأسود الفاخر",
    description: "Industrial obsidian carbon lattice with sweeping specular chrome light beams and precision metallic shadows.",
    descriptionAr: "شبكة كربونية أوبسيديان صناعية داكنة مع حزم إضاءة كرومية مصقولة وظلال معدنية فائقة الأناقة.",
    category: "cyber",
    rarity: "epic",
    badge: "Industrial",
    badgeAr: "صناعي متقدم",
    colors: {
      primary: "#71717a",
      secondary: "#27272a",
      accent: "#a1a1aa",
      glow: "rgba(161, 161, 170, 0.25)",
      particles: "#e4e4e7",
      overlay: "rgba(24, 24, 27, 0.35)",
    },
    animationType: "drift",
    performanceTier: "low",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 5,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: false,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "digital-rain",
    name: "Digital Matrix",
    nameAr: "المصفوفة الرقمية",
    description: "Vertical cascading phosphor green and mint cyber data streams with subtle terminal flicker and ambient phosphorescence.",
    descriptionAr: "شلالات بيانات سيبرانية عمودية باللون الفسفوري الأخضر والنعناعي مع وميض طرفي هادئ وتوهج أنيق.",
    category: "animated",
    rarity: "epic",
    badge: "Terminal",
    badgeAr: "طرفية رقمية",
    colors: {
      primary: "#22c55e",
      secondary: "#15803d",
      accent: "#4ade80",
      glow: "rgba(34, 197, 94, 0.35)",
      particles: "#86efac",
      overlay: "rgba(20, 83, 45, 0.25)",
    },
    animationType: "stream",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 6,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "neon-energy",
    name: "Neon Energy",
    nameAr: "طاقة النيون",
    description: "High-voltage bio-luminescent neon energy currents pulsating rhythmically across responsive topographic contours.",
    descriptionAr: "تيارات طاقة نيون حيوية عالية التوهج تنبض بإيقاع سلس عبر تضاريس ضوئية متجاوبة.",
    category: "neon",
    rarity: "rare",
    badge: "Vibrant",
    badgeAr: "نيون ساطع",
    colors: {
      primary: "#10b981",
      secondary: "#0d9488",
      accent: "#2dd4bf",
      glow: "rgba(45, 212, 191, 0.4)",
      particles: "#99f6e4",
      overlay: "rgba(19, 78, 74, 0.25)",
    },
    animationType: "pulse",
    performanceTier: "low",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 7,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: false,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "starfield-void",
    name: "Starfield Void",
    nameAr: "حقل النجوم السحيق",
    description: "Deep atmospheric void with multidimensional twinkling stars, distant wandering comets, and quiet gravitational depth.",
    descriptionAr: "فضاء سحيق هادئ مع نجوم متلألئة متعددة الأعماق وشُهُب بعيدة وعمق بصري انسيابي.",
    category: "cosmic",
    rarity: "rare",
    badge: "Deep Space",
    badgeAr: "فضاء سحيق",
    colors: {
      primary: "#38bdf8",
      secondary: "#1e1b4b",
      accent: "#93c5fd",
      glow: "rgba(56, 189, 248, 0.3)",
      particles: "#f8fafc",
      overlay: "rgba(15, 23, 42, 0.35)",
    },
    animationType: "drift",
    performanceTier: "low",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 8,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "glass-light",
    name: "Frosted Glass Caustics",
    nameAr: "الزجاج المثلج",
    description: "Pristine frosted glassmorphic caustics with floating soft luminous orbs and subtle diffused refraction halos.",
    descriptionAr: "انكسارات زجاجية مثلجة فائقة النقاء (Glassmorphism) مع كرات ضوء عائمة هادئة وهالات ضبابية أنيقة.",
    category: "minimal",
    rarity: "common",
    badge: "Pristine",
    badgeAr: "نقي مينيمال",
    colors: {
      primary: "#ffffff",
      secondary: "#94a3b8",
      accent: "#f1f5f9",
      glow: "rgba(255, 255, 255, 0.2)",
      particles: "#cbd5e1",
      overlay: "rgba(30, 41, 59, 0.2)",
    },
    animationType: "drift",
    performanceTier: "low",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 9,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: false,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "dark-crystal",
    name: "Dark Amethyst Crystal",
    nameAr: "بلور الجمشت الداكن",
    description: "Faceted amethyst geometric prism shards rotating slowly inside a deep violet resonance field.",
    descriptionAr: "شظايا بلورية هندسية من الجمشت البنفسجي تدور ببطء وتناغم داخل حقل رنين فلكي فاخر.",
    category: "luxury",
    rarity: "rare",
    badge: "Crystalline",
    badgeAr: "بلوري فاخر",
    colors: {
      primary: "#9333ea",
      secondary: "#581c87",
      accent: "#c084fc",
      glow: "rgba(147, 51, 234, 0.35)",
      particles: "#e9d5ff",
      overlay: "rgba(59, 7, 100, 0.3)",
    },
    animationType: "pulse",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 10,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "liquid-aurora",
    name: "Liquid Aurora Waves",
    nameAr: "أمواج الشفق السائل",
    description: "Fluid chromatic plasma waves undulating smoothly across the surface with iridescent oceanic fluid motion.",
    descriptionAr: "أمواج بلازما شفقية انسيابية تتدفق بحركة مائعة ناعمة وتدرجات لونية قزحية ساحرة.",
    category: "aurora",
    rarity: "epic",
    badge: "Fluidic",
    badgeAr: "سائل انسيابي",
    colors: {
      primary: "#06b6d4",
      secondary: "#8b5cf6",
      accent: "#3b82f6",
      glow: "rgba(6, 182, 212, 0.35)",
      particles: "#a5f3fc",
      overlay: "rgba(12, 74, 110, 0.25)",
    },
    animationType: "wave",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 11,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "royal-ambient",
    name: "Royal Champagne Gold",
    nameAr: "الذهب الإمبراطوري",
    description: "Imperial 24k champagne gold particulate shimmer with warm ambient radiance, crest motes, and luxury caustics.",
    descriptionAr: "بريق ذهبي إمبراطوري عيار 24 قيراط بلون الشمبانيا مع جزيئات متلألئة وإضاءة دافئة فائقة الفخامة.",
    category: "luxury",
    rarity: "legendary",
    badge: "Crown Class",
    badgeAr: "الفئة الملكية",
    colors: {
      primary: "#eab308",
      secondary: "#713f12",
      accent: "#facc15",
      glow: "rgba(234, 179, 8, 0.4)",
      particles: "#fef08a",
      overlay: "rgba(66, 32, 6, 0.25)",
    },
    animationType: "shimmer",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 12,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  // ── 5 DRAGONS ──────────────────────────────────────────────
  {
    effectId: "emerald-dragon",
    name: "Emerald Dragon",
    nameAr: "تنين الزمرد",
    description: "Majestic sovereign emerald dragon radiating celestial plasma breath, piercing jade eyes, atmospheric mist, and ancient draconian energy.",
    descriptionAr: "تنين زمردي سيادي مهيب ينفث بلازما خضراء ساحرة مع عيون يشم متوهجة وضباب أثيري وطاقة تنانين قديمة متناسقة مع هوية WhiterChat.",
    category: "dragon",
    rarity: "legendary",
    badge: "Sovereign Dragon",
    badgeAr: "تنين سيادي",
    colors: {
      primary: "#10b981",
      secondary: "#064e3b",
      accent: "#34d399",
      glow: "rgba(52, 211, 153, 0.45)",
      particles: "#6ee7b7",
      overlay: "rgba(6, 78, 59, 0.3)",
    },
    animationType: "pulse",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 13,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "inferno-dragon",
    name: "Inferno Dragon",
    nameAr: "تنين الجحيم الناري",
    description: "Fearsome magma dragon visage crowned with molten horns, cascading fiery embers, volcanic smoke plumes, and a cinematic furnace glow.",
    descriptionAr: "تنين ناري بركاني فائق الهيبة بقرون منصهرة وجمرات متصاعدة بهدوء وألسنة لهب سينمائية دافئة دون فوضى.",
    category: "dragon",
    rarity: "legendary",
    badge: "Volcanic Wyrm",
    badgeAr: "تنين بركاني",
    colors: {
      primary: "#ef4444",
      secondary: "#991b1b",
      accent: "#f59e0b",
      glow: "rgba(239, 68, 68, 0.45)",
      particles: "#fde047",
      overlay: "rgba(69, 10, 10, 0.3)",
    },
    animationType: "drift",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 14,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "shadow-dragon",
    name: "Shadow Dragon",
    nameAr: "تنين الظلال",
    description: "Enigmatic obsidian shadow dragon shrouded in curled dark smoke tendrils, piercing amethyst gaze, and opulent royal violet twilight.",
    descriptionAr: "تنين مظلم غامض محاط بتموجات دخان أسود فخم وتوهج بنفسجي ملكي هادئ مع نظرة ثاقبة تمنح البروفايل هيبة لا مثيل لها.",
    category: "dragon",
    rarity: "legendary",
    badge: "Void Wyrm",
    badgeAr: "تنين الفراغ",
    colors: {
      primary: "#8b5cf6",
      secondary: "#3b0764",
      accent: "#c084fc",
      glow: "rgba(139, 92, 246, 0.4)",
      particles: "#e9d5ff",
      overlay: "rgba(24, 9, 44, 0.35)",
    },
    animationType: "pulse",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 15,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "storm-dragon",
    name: "Storm Dragon",
    nameAr: "تنين العواصف والبرق",
    description: "Tempest dragon charging through atmospheric thunderclouds with electric cyan arcs, floating electrostatic particles, and teal lightning accents.",
    descriptionAr: "تنين العواصف الخارق محاط بسحب رعدية داكنة وتفريغات برق زرقاء سيانية انسيابية غير مزعجة وجزيئات كهروستاتيكية عائمة.",
    category: "dragon",
    rarity: "legendary",
    badge: "Tempest Wyrm",
    badgeAr: "تنين العواصف",
    colors: {
      primary: "#0ea5e9",
      secondary: "#0369a1",
      accent: "#38bdf8",
      glow: "rgba(14, 165, 233, 0.45)",
      particles: "#7dd3fc",
      overlay: "rgba(8, 47, 73, 0.3)",
    },
    animationType: "wave",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 16,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "celestial-dragon",
    name: "Celestial Dragon",
    nameAr: "التنين الكوني الأسطوري",
    description: "Mythical star-forged celestial dragon weaving through deep nebula dust, glistening astral constellations, and iridescent orbital stardust.",
    descriptionAr: "تنين كوني أسطوري منسوج من ضوء النجوم وسديم الفضاء العميق مع غبار فلكي ومدارات كوكبية مبهرة.",
    category: "dragon",
    rarity: "legendary",
    badge: "Astral Wyrm",
    badgeAr: "تنين فلكي",
    colors: {
      primary: "#6366f1",
      secondary: "#1e1b4b",
      accent: "#2dd4bf",
      glow: "rgba(99, 102, 241, 0.45)",
      particles: "#a5f3fc",
      overlay: "rgba(15, 23, 42, 0.3)",
    },
    animationType: "orbit",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 17,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },

  // ── 5 ANIMALS ──────────────────────────────────────────────
  {
    effectId: "royal-lion",
    name: "Royal Lion",
    nameAr: "الأسد الملكي الفاخر",
    description: "Imperial solar lion crowned with an ornate golden diadem, radiating warm champagne aureole rays, amber eye highlights, and royal particulate depth.",
    descriptionAr: "أسد ملكي إمبراطوري بتاج شمسي ذهبي وهالة دافئة من الضوء الملكي وجزيئات ذهبية عائمة تفيض بالسيادة والأناقة.",
    category: "animal",
    rarity: "legendary",
    badge: "Imperial Monarch",
    badgeAr: "عاهل إمبراطوري",
    colors: {
      primary: "#f59e0b",
      secondary: "#78350f",
      accent: "#fbbf24",
      glow: "rgba(245, 158, 11, 0.45)",
      particles: "#fef08a",
      overlay: "rgba(69, 26, 3, 0.3)",
    },
    animationType: "shimmer",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 18,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "shadow-panther",
    name: "Shadow Panther",
    nameAr: "البانثر الليلي الأنيق",
    description: "Sleek noir panther peering through midnight velvet mist with hypnotic emerald-cyan feline eyes and smooth stealth atmospheric depth.",
    descriptionAr: "بانثر أسود فائق الرشاقة والأناقة يتربص في ضباب الليل المخملي مع عيون زمردية زرقاء آسرة وحركة ظل انسيابية.",
    category: "animal",
    rarity: "epic",
    badge: "Midnight Apex",
    badgeAr: "مفترس ليلي",
    colors: {
      primary: "#10b981",
      secondary: "#09090b",
      accent: "#06b6d4",
      glow: "rgba(16, 185, 129, 0.35)",
      particles: "#5eead4",
      overlay: "rgba(9, 9, 11, 0.45)",
    },
    animationType: "drift",
    performanceTier: "low",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 19,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "spirit-wolf",
    name: "Spirit Wolf",
    nameAr: "الذئب الروحي الأثيري",
    description: "Ethereal spirit wolf silhouette howling beneath celestial moonlight, veiled in floating spirit orbs, luminous azure fur edges, and nocturnal mist.",
    descriptionAr: "ذئب روحي أثيري يعوي تحت ضوء القمر محاطًا بضباب أزرق سماوي وجزيئات ضوء روحية وأطراف متوهجة فائقة النقاء.",
    category: "animal",
    rarity: "epic",
    badge: "Astral Beast",
    badgeAr: "ذئب أثيري",
    colors: {
      primary: "#06b6d4",
      secondary: "#083344",
      accent: "#22d3ee",
      glow: "rgba(6, 182, 212, 0.4)",
      particles: "#a5f3fc",
      overlay: "rgba(8, 47, 73, 0.28)",
    },
    animationType: "wave",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 20,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "arctic-wolf",
    name: "Arctic Wolf",
    nameAr: "ذئب الجليد القطبي",
    description: "Noble polar wolf traversing subzero tundra blizzard, frosted crystalline ruff, drifting diamond snowflakes, and glacial pale blue radiance.",
    descriptionAr: "ذئب جليدي قطبي شامخ وسط عاصفة ثلجية هادئة وجزيئات جليد ألماسية متساقطة وتوهج ثلجي أزرق نقي.",
    category: "animal",
    rarity: "epic",
    badge: "Frostfang",
    badgeAr: "ناب الجليد",
    colors: {
      primary: "#38bdf8",
      secondary: "#0c4a6e",
      accent: "#93c5fd",
      glow: "rgba(56, 189, 248, 0.4)",
      particles: "#ffffff",
      overlay: "rgba(8, 47, 73, 0.25)",
    },
    animationType: "drift",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 21,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "golden-eagle",
    name: "Golden Eagle",
    nameAr: "النسر الذهبي السيادي",
    description: "Majestic golden eagle soaring across mountain sunburst heights with outstretched thermal wings, gilded light caustics, and windborne golden flecks.",
    descriptionAr: "نسر ذهبي سيادي بأجنحة شامخة تلامس أشعة الشمس الذهبية عند قمم الجبال مع لمسات ضوئية وحبيبات ريش ذهبية طافية.",
    category: "animal",
    rarity: "epic",
    badge: "Sky Sovereign",
    badgeAr: "سيد السماء",
    colors: {
      primary: "#eab308",
      secondary: "#713f12",
      accent: "#fde047",
      glow: "rgba(234, 179, 8, 0.45)",
      particles: "#fef9c3",
      overlay: "rgba(66, 32, 6, 0.25)",
    },
    animationType: "shimmer",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 22,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },

  // ── 5 MYTHICAL CREATURES ────────────────────────────────────
  {
    effectId: "phoenix-rebirth",
    name: "Phoenix Rebirth",
    nameAr: "طائر الفينيق المتجدد",
    description: "Legendary immortal firebird rising from cosmic ashes with spread solar flame wings, radiant rebirth aura, and upward-surging golden-crimson embers.",
    descriptionAr: "طائر الفينيق الأسطوري ينهض من رماده بأجنحة لهب شمسية ممتدة مع هالة تجدد ساطعة وجمرات ذهبية وحمراء متصاعدة بسحر.",
    category: "mythical",
    rarity: "legendary",
    badge: "Eternal Flame",
    badgeAr: "الشعلة الأبدية",
    colors: {
      primary: "#f97316",
      secondary: "#7c2d12",
      accent: "#fbbf24",
      glow: "rgba(249, 115, 22, 0.45)",
      particles: "#fed7aa",
      overlay: "rgba(67, 20, 7, 0.3)",
    },
    animationType: "pulse",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 23,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "celestial-pegasus",
    name: "Celestial Pegasus",
    nameAr: "بيغاسوس النجمي",
    description: "Graceful celestial winged pegasus with starlight feather plumes, silver-violet astral dust trail, and glowing constellation nodes.",
    descriptionAr: "حصان أسطوري مجنح من أضواء المجرات بريش كوني ناصع وذيل من الغبار النجمي الفضي البنفسجي وعناقيد فلكية متلألئة.",
    category: "mythical",
    rarity: "legendary",
    badge: "Astral Steed",
    badgeAr: "حصان فلكي",
    colors: {
      primary: "#a855f7",
      secondary: "#3b0764",
      accent: "#e879f9",
      glow: "rgba(168, 85, 247, 0.4)",
      particles: "#f5d0fe",
      overlay: "rgba(36, 10, 63, 0.3)",
    },
    animationType: "shimmer",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 24,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "leviathan-abyss",
    name: "Leviathan Abyss",
    nameAr: "وحش الأعماق الأسطوري",
    description: "Colossal abyssal leviathan gliding through dark ocean depths with bioluminescent cyan dorsal crests, underwater caustics, and marine spore bubbles.",
    descriptionAr: "كائن ليفياثان الأعماق السحيق يسبح في مياه المحيط المظلمة مع زعانف متوهجة ببيولومينسنت سياني وانكسارات أشعة ضوئية وفقاعات بحرية ساحرة.",
    category: "mythical",
    rarity: "legendary",
    badge: "Deep Ocean",
    badgeAr: "أعماق المحيط",
    colors: {
      primary: "#06b6d4",
      secondary: "#042f2e",
      accent: "#22d3ee",
      glow: "rgba(6, 182, 212, 0.45)",
      particles: "#67e8f9",
      overlay: "rgba(4, 47, 46, 0.35)",
    },
    animationType: "wave",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 25,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "frost-griffin",
    name: "Frost Griffin",
    nameAr: "الغريفين الجليدي",
    description: "Apex glacial griffin carved of sharp diamond ice facets and frozen azure feathers, generating swirling subzero blizzard crystals and crisp polar highlights.",
    descriptionAr: "غريفين أسطوري منحوت من جليد الألماس الصقيل والريش الأزرق المثلج مع بلورات صقيع متطايرة وتوهج قطبي فائق النقاء.",
    category: "mythical",
    rarity: "legendary",
    badge: "Glacial Beast",
    badgeAr: "وحش جليدي",
    colors: {
      primary: "#0284c7",
      secondary: "#082f49",
      accent: "#7dd3fc",
      glow: "rgba(2, 132, 199, 0.4)",
      particles: "#e0f2fe",
      overlay: "rgba(8, 47, 73, 0.28)",
    },
    animationType: "pulse",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 26,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "solar-basilisk",
    name: "Solar Basilisk",
    nameAr: "باسيليسك الشمس الذهبي",
    description: "Ancient solar serpent monarch coiled within a brilliant solar corona, emitting hypnotic golden gaze rays, molten desert twilight, and shimmering gilded dust.",
    descriptionAr: "ثعبان الشمس الباسيليسك الأسطوري يلتف في هالة قرص الشمس مع نظرة ذهبية مغناطيسية وغبار ذهبي صحراوي ملتهب وتدرجات كهرمانية غنية.",
    category: "mythical",
    rarity: "legendary",
    badge: "Solar Serpent",
    badgeAr: "ثعبان الشمس",
    colors: {
      primary: "#eab308",
      secondary: "#78350f",
      accent: "#fb923c",
      glow: "rgba(234, 179, 8, 0.45)",
      particles: "#fef08a",
      overlay: "rgba(69, 26, 3, 0.3)",
    },
    animationType: "wave",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 27,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },

  // ── 5 COSMIC / DARK ─────────────────────────────────────────
  {
    effectId: "singularity-horizon",
    name: "Singularity Horizon",
    nameAr: "أفق الحدث والثقب الأسود",
    description: "Supermassive gravitational singularity bending spacetime with an ultra-bright relativistic accretion disk, dark matter event horizon, and orbiting photon rings.",
    descriptionAr: "ثقب أسود فلكي خارق يحني نسيج الزمكان بقرص تراكمي مضيء فائق الجاذبية مع أفق حدث مظلم وحلقات فوتونية تدور حول الفراغ السحيق.",
    category: "dark",
    rarity: "legendary",
    badge: "Cosmic Abyss",
    badgeAr: "هاوية كونية",
    colors: {
      primary: "#8b5cf6",
      secondary: "#09090b",
      accent: "#ec4899",
      glow: "rgba(139, 92, 246, 0.45)",
      particles: "#f472b6",
      overlay: "rgba(9, 9, 11, 0.5)",
    },
    animationType: "orbit",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 28,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "cyber-dragon",
    name: "Cybernetic Neon Dragon",
    nameAr: "تنين السايبر الميكانيكي",
    description: "Futuristic biomechanical dragon chassis equipped with neon green holographic circuit traces, tactical HUD scanlines, and digital telemetry pulses.",
    descriptionAr: "تنين ميكانيكي سايبر مستقبلي بحراشف دوائر إلكترونية نيون خضراء وخطوط مسح HUD تكتيكية ومسارات ألياف ضوئية فائقة التطور.",
    category: "dark",
    rarity: "epic",
    badge: "Mecha Bioform",
    badgeAr: "كائن ميكانيكي",
    colors: {
      primary: "#10b981",
      secondary: "#022c22",
      accent: "#06b6d4",
      glow: "rgba(16, 185, 129, 0.45)",
      particles: "#34d399",
      overlay: "rgba(2, 44, 34, 0.35)",
    },
    animationType: "scanline",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 29,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "void-sovereign",
    name: "Void Sovereign",
    nameAr: "السيادة الكونية المظلمة",
    description: "Imperial dark monarch crown suspended across a total solar eclipse, encircled by levitating obsidian monolith shards, deep amethyst nebula, and royal corona light.",
    descriptionAr: "تاج الملك المظلم يطفو فوق كسوف شمسي كلي محاطًا بشظايا حجر الأوبسيديان المعلقة في انعدام الجاذبية مع هالة بنفسجية ساحرة.",
    category: "dark",
    rarity: "legendary",
    badge: "Eclipse Crown",
    badgeAr: "تاج الكسوف",
    colors: {
      primary: "#7c3aed",
      secondary: "#1e1b4b",
      accent: "#a855f7",
      glow: "rgba(124, 58, 237, 0.45)",
      particles: "#ddd6fe",
      overlay: "rgba(15, 10, 35, 0.4)",
    },
    animationType: "pulse",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 30,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "quantum-phantom",
    name: "Quantum Phantom",
    nameAr: "الطيف الكمي الأثيري",
    description: "Multidimensional quantum entity pulsating between parallel states, casting prismatic wave interference fringes, chromatic aberration shadows, and spectral echoes.",
    descriptionAr: "طيف كمي متعدد الأبعاد يتماوج بترددات ضوئية فائقة الدقة مع تداخلات موجية طيفية وظلال هولوغرافية انكسارية ساحرة.",
    category: "dark",
    rarity: "epic",
    badge: "Spectral Wave",
    badgeAr: "موجة طيفية",
    colors: {
      primary: "#c084fc",
      secondary: "#3b0764",
      accent: "#38bdf8",
      glow: "rgba(192, 132, 252, 0.4)",
      particles: "#e9d5ff",
      overlay: "rgba(24, 9, 44, 0.3)",
    },
    animationType: "drift",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 31,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  {
    effectId: "supernova-core",
    name: "Supernova Astral Core",
    nameAr: "نواة السوبرنوفا المتفجرة",
    description: "Stellar nucleus undergoing violent supernova nucleosynthesis, sending forth expanding chromatic shockwave rings, radiant filament arms, and high-velocity star dust.",
    descriptionAr: "نواة نجمية في ذروة انفجار سوبرنوفا كوني مذهل مع حلقات صدمية متوسعة وأذرع بلازما متوهجة وغبار كوني عالي السرعة.",
    category: "dark",
    rarity: "legendary",
    badge: "Cosmic Burst",
    badgeAr: "انفجار فلكي",
    colors: {
      primary: "#f43f5e",
      secondary: "#4c0519",
      accent: "#fbbf24",
      glow: "rgba(244, 63, 94, 0.45)",
      particles: "#fef08a",
      overlay: "rgba(35, 3, 11, 0.35)",
    },
    animationType: "pulse",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 32,
    layersConfig: {
      baseBackground: true,
      ambientGradient: true,
      lightGlow: true,
      particles: true,
      atmosphericMesh: true,
      interactivePointer: true,
      vignetteOverlay: true,
    },
  },
  // ── NEW COLLECTION (21 to 40) ──────────────────────────────
  // ── DRAGONS (21 to 25) ──
  {
    effectId: "infernal-wyrm",
    name: "Infernal Wyrm",
    nameAr: "التنين البركاني العتيق",
    description: "Ancient fiery wyrm ascending from deep volcanic fissures with streaming trails of orange ember plasma and basalt smoke.",
    descriptionAr: "تنين بركاني سحيق يصعد من شقوق الحمم البركانية المتفجرة مع خطوط بلازما برتقالية ودخان بازلتي مهيب.",
    extendedDescription: "A primal subterranean wyrm forged in deep molten magma chambers. Features cascading volcanic ember sparks, undulating heat haze, and glowing obsidian scales that radiate power.",
    extendedDescriptionAr: "تنين بركاني أولي صُهر في أعماق غرف الصهارة البركانية. يتميز بشرارات جمر متصاعدة، ضباب حراري سينمائي، وحراشف بازلتية متوهجة تعكس القوة والهيبة.",
    tags: ["dragon", "fire", "magma", "legendary", "animated", "volcanic"],
    category: "dragon",
    rarity: "legendary",
    badge: "Magma Wyrm",
    badgeAr: "تنين الحمم",
    colors: {
      primary: "#f97316",
      secondary: "#7c2d12",
      accent: "#fbbf24",
      glow: "rgba(249, 115, 22, 0.45)",
      particles: "#fde047",
      overlay: "rgba(67, 20, 7, 0.3)",
    },
    animationType: "drift",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 33,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "frostfire-dragon",
    name: "Frostfire Dragon",
    nameAr: "تنين جليد النار",
    description: "Elemental dragon fusing cryogenic subzero blizzard frost with intense azure flame breath and diamond icicles.",
    descriptionAr: "تنين عنصري أسطوري يدمج صقيع العواصف الثلجية مع أنفاس اللهب الأزرق الحارق وبلورات الجليد الألماسية.",
    extendedDescription: "A rare paradoxical beast commanding both absolute cold and burning azure flame. Its crest shimmers with alternating frost needles and blue thermal waves, creating a spellbinding contrast.",
    extendedDescriptionAr: "وحش أسطوري نادر يجمع بين البرودة المطلقة واللهب الأزرق المستعر. تتلألأ قمة رأسه بإبر الجليد وأمواج الحرارة الزرقاء لتصنع تباينًا بصريًا ساحرًا.",
    tags: ["dragon", "ice", "fire", "elemental", "legendary", "frost"],
    category: "dragon",
    rarity: "legendary",
    badge: "Dual Element",
    badgeAr: "عنصر مزدوج",
    colors: {
      primary: "#06b6d4",
      secondary: "#1e3a8a",
      accent: "#38bdf8",
      glow: "rgba(6, 182, 212, 0.45)",
      particles: "#e0f2fe",
      overlay: "rgba(12, 74, 110, 0.3)",
    },
    animationType: "pulse",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 34,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "emerald-ancient",
    name: "Emerald Ancient",
    nameAr: "التنين الزمردي القديم",
    description: "Primeval arboreal dragon elder draped in bioluminescent moss, sovereign jade horns, and verdant nature energy.",
    descriptionAr: "تنين معمر أسطوري مغطى بطحالب بيولومينسنت متوهجة وقرون يشم سيادية وطاقة غابات زمردية نقية.",
    extendedDescription: "Awakened from millennial slumber beneath ancestral canopies, this elder dragon radiates peaceful sovereign energy, floating jade spores, and emerald life force matching WhiterChat's sovereign aesthetic.",
    extendedDescriptionAr: "استيقظ من سبات دام آلاف السنين تحت ظلال الغابات العتيقة، يشع هذا التنين بهالة خضراء سيادية وأبواغ يشم عائمة تتناغم مع هوية WhiterChat الخضراء.",
    tags: ["dragon", "emerald", "nature", "legendary", "ancient", "green"],
    category: "dragon",
    rarity: "legendary",
    badge: "Primeval Elder",
    badgeAr: "تنين معمر",
    colors: {
      primary: "#059669",
      secondary: "#064e3b",
      accent: "#34d399",
      glow: "rgba(5, 150, 105, 0.45)",
      particles: "#a7f3d0",
      overlay: "rgba(6, 78, 59, 0.3)",
    },
    animationType: "wave",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 35,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "lunar-dragon",
    name: "Lunar Dragon",
    nameAr: "تنين القمر الفضي",
    description: "Celestial serpentine dragon gliding through a silver-blue lunar halo with radiating moonbeam caustics and pearl stardust.",
    descriptionAr: "تنين قمري انسيابي ينساب عبر هالة ضوء القمر الفضية-الزرقاء مع انكسارات شعاعية وغبار لؤلؤي فلكي.",
    extendedDescription: "Guardian of the moonlit night skies, moving with fluid grace while casting soft silver-cyan radiance, orbital halo ripples, and ethereal moonstone dust motes.",
    extendedDescriptionAr: "حارس سماء الليل المقمرة، يتحرك برشاقة انسيابية فائقة ناشرًا إضاءة فضية-سيانية ناعمة وتموجات هالة مدارية مع حبيبات غبار حجر القمر.",
    tags: ["dragon", "lunar", "moon", "silver", "legendary", "celestial"],
    category: "dragon",
    rarity: "legendary",
    badge: "Lunar Wyrm",
    badgeAr: "تنين قمري",
    colors: {
      primary: "#93c5fd",
      secondary: "#1e293b",
      accent: "#e2e8f0",
      glow: "rgba(147, 197, 253, 0.4)",
      particles: "#f8fafc",
      overlay: "rgba(15, 23, 42, 0.3)",
    },
    animationType: "orbit",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 36,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "thunder-drake",
    name: "Thunder Drake",
    nameAr: "دريك الصواعق الهادر",
    description: "High-altitude winged drake shrouded in charged dark cumulus clouds with rapid electric corona discharges and teal lightning spurs.",
    descriptionAr: "دريك مجنح يحلق في أعالي السحب الركامية المشحونة مع ومضات كورونا كهربائية هادئة وتشعبات صواعق تيل أنيقة.",
    extendedDescription: "Riding the apex of supersonic thunderstorm fronts, the Thunder Drake discharges controlled electrostatic arcs that crackle smoothly across dark tempest silhouettes.",
    extendedDescriptionAr: "يمتطي قمم جبهات العواصف الرعدية، يطلق تفريغات كهروستاتيكية سلسة تومض برقي ونعومة عبر سحب العاصفة الداكنة دون أي إزعاج للعين.",
    tags: ["dragon", "storm", "lightning", "electric", "legendary"],
    category: "dragon",
    rarity: "legendary",
    badge: "Apex Tempest",
    badgeAr: "قمة العاصفة",
    colors: {
      primary: "#0284c7",
      secondary: "#082f49",
      accent: "#22d3ee",
      glow: "rgba(2, 132, 199, 0.45)",
      particles: "#7dd3fc",
      overlay: "rgba(8, 47, 73, 0.3)",
    },
    animationType: "scanline",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 37,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },

  // ── ANIMALS (26 to 30) ──
  {
    effectId: "silver-wolf",
    name: "Silver Wolf",
    nameAr: "الذئب الفضي المهيب",
    description: "Noble silver timber wolf silhouette standing atop a moonlit precipice with shimmering metallic fur highlights and glowing platinum eyes.",
    descriptionAr: "ذئب غابات فضي نبيل يقف بشموخ فوق قمة صخرية مقمرة مع لمعان فراء معدني وعيون بلاتينية متقدة.",
    extendedDescription: "The sovereign leader of the northern pack, framed by cold silver moonlight, metallic hair caustics, and crisp platinum particulate shimmer.",
    extendedDescriptionAr: "قائد قطعان الشمال السيادي، محاط بنور القمر الفضي البارد ولمسات ضوء معدنية وبريق جزيئات بلاتينية يعكس القيادة والشموخ.",
    tags: ["animal", "wolf", "silver", "moon", "epic", "alpha"],
    category: "animal",
    rarity: "epic",
    badge: "Silver Alpha",
    badgeAr: "ألفا فضي",
    colors: {
      primary: "#cbd5e1",
      secondary: "#334155",
      accent: "#f8fafc",
      glow: "rgba(203, 213, 225, 0.4)",
      particles: "#ffffff",
      overlay: "rgba(15, 23, 42, 0.3)",
    },
    animationType: "shimmer",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 38,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "crimson-tiger",
    name: "Crimson Tiger",
    nameAr: "النمر القرمزي المفترس",
    description: "Ferocious shadow tiger with burning crimson stripes, glowing amber fangs, creeping red twilight fog, and stalking predator poise.",
    descriptionAr: "نمر ظلال كاسر بخطوط قرمزية متقدة وأنياب كهرمانية متوهجة وضباب شفق أحمر زاحف في وضعية التربص.",
    extendedDescription: "Prowling through bamboo twilight, the Crimson Tiger exudes untamed primal power with rhythmically pulsing tiger stripes and warm amber feline eyes.",
    extendedDescriptionAr: "يتربص عبر شفق الغابات الكثيفة، يفيض النمر القرمزي بالقوة الطبيعية الجامحة مع خطوط جسد تنبض بإيقاع هادئ وعيون قطة كهرمانية دافئة.",
    tags: ["animal", "tiger", "crimson", "predator", "epic", "fire"],
    category: "animal",
    rarity: "epic",
    badge: "Apex Predator",
    badgeAr: "مفترس مهيب",
    colors: {
      primary: "#e11d48",
      secondary: "#4c0519",
      accent: "#fb923c",
      glow: "rgba(225, 29, 72, 0.45)",
      particles: "#fda4af",
      overlay: "rgba(35, 3, 11, 0.35)",
    },
    animationType: "pulse",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 39,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "arctic-fox",
    name: "Arctic Fox",
    nameAr: "الثعلب القطبي الأنيق",
    description: "Enchanting polar kitsune fox with bushy frosted tail tips, floating aurora motes, soft diamond snow flurry, and curious cyan eyes.",
    descriptionAr: "ثعلب قطبي ساحر بذيل كثيف مثلج وجزيئات شفق عائمة وتساقط ثلج ناعم مع عيون سيانية فضولية ناصعة.",
    extendedDescription: "A playful spirit of the high tundra, surrounded by gentle drifting snow flurries, soft cyan rim light, and delicate winter magic.",
    extendedDescriptionAr: "روح مرحة من سهول التندرا القطبية، محاط بنفحات ثلجية لطيفة وإضاءة حواف سيانية ناعمة وسحر شتوي هادئ وأنيق.",
    tags: ["animal", "fox", "arctic", "ice", "rare", "cute"],
    category: "animal",
    rarity: "rare",
    badge: "Tundra Kitsune",
    badgeAr: "ثعلب التندرا",
    colors: {
      primary: "#38bdf8",
      secondary: "#0c4a6e",
      accent: "#bae6fd",
      glow: "rgba(56, 189, 248, 0.35)",
      particles: "#ffffff",
      overlay: "rgba(8, 47, 73, 0.25)",
    },
    animationType: "drift",
    performanceTier: "low",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 40,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "night-raven",
    name: "Night Raven",
    nameAr: "غراب الليل الغامض",
    description: "Ominous midnight raven perched amidst swirling obsidian feather motes, deep purple atmospheric twilight, and glistening amethyst beak sheen.",
    descriptionAr: "غراب ليلي غامض يحلق وسط تطاير ريش أوبسيديان أسود وشفق أرجواني سحيق مع لمعان منقار جمشتي.",
    extendedDescription: "The silent observer of ancient secrets, draped in velvety purple dusk and dark raven feather silhouettes that drift gracefully down the profile banner.",
    extendedDescriptionAr: "المراقب الصامت للأسرار القديمة، محاط بشفق أرجواني مخملي وظلال ريش غراب تتهادى برقة وانسيابية فوق مساحة البروفايل.",
    tags: ["animal", "raven", "dark", "gothic", "epic", "shadow"],
    category: "animal",
    rarity: "epic",
    badge: "Shadow Wing",
    badgeAr: "جناح الظل",
    colors: {
      primary: "#7c3aed",
      secondary: "#2e1065",
      accent: "#a855f7",
      glow: "rgba(124, 58, 237, 0.4)",
      particles: "#ddd6fe",
      overlay: "rgba(15, 10, 35, 0.35)",
    },
    animationType: "drift",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 41,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "spirit-stag",
    name: "Spirit Stag",
    nameAr: "الأيل الروحي العظيم",
    description: "Majestic forest monarch stag with branching luminous crystal antlers radiating soft emerald and gold life spores through an enchanted glade.",
    descriptionAr: "أيل ملكي شامخ بقرون بلورية مضيئة تنبثق منها أبواغ حياة زمردية وذهبية ناعمة وسط غابة مسحورة.",
    extendedDescription: "Guardian deity of primeval sanctuaries, adorned with towering crystalline antlers that channel gentle emerald flora waves and sunlit golden particles.",
    extendedDescriptionAr: "الحارس الأسطوري للمحميات الطبيعية الخالدة، يتزين بقرون بلورية شامخة ترسل موجات حياة خضراء ناعمة وجزيئات ذهبية مشمسة.",
    tags: ["animal", "stag", "forest", "nature", "legendary", "spirit"],
    category: "animal",
    rarity: "legendary",
    badge: "Forest Deity",
    badgeAr: "حارس الغابة",
    colors: {
      primary: "#10b981",
      secondary: "#064e3b",
      accent: "#facc15",
      glow: "rgba(16, 185, 129, 0.45)",
      particles: "#fef08a",
      overlay: "rgba(6, 78, 59, 0.3)",
    },
    animationType: "wave",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 42,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },

  // ── MYTHICAL (31 to 35) ──
  {
    effectId: "moon-griffin",
    name: "Moon Griffin",
    nameAr: "غريفين ضوء القمر",
    description: "Mythical lunar griffin with silver eagle plumage and pearlescent lion hindquarters bathed in midnight lunar caustics and drifting moon dust.",
    descriptionAr: "غريفين قمري أسطوري بريش نسر فضي وأطراف أسد لؤلؤية يسبح في انكسارات ضوء القمر الساحر ورذاذ فلكي.",
    extendedDescription: "Soaring between lunar crescents and celestial clouds, the Moon Griffin reflects pearlescent silver radiance with crisp wing feather highlights and drifting astral motes.",
    extendedDescriptionAr: "يحلق بين أهلة القمر وسحب السماء الصافية، يعكس الغريفين بريقًا فضيًا لؤلؤيًا مع تفاصيل ريش ناصعة وجزيئات فلكية عائمة.",
    tags: ["mythical", "griffin", "lunar", "moon", "legendary", "silver"],
    category: "mythical",
    rarity: "legendary",
    badge: "Lunar Behemoth",
    badgeAr: "غريفين قمري",
    colors: {
      primary: "#94a3b8",
      secondary: "#1e293b",
      accent: "#e2e8f0",
      glow: "rgba(148, 163, 184, 0.4)",
      particles: "#ffffff",
      overlay: "rgba(15, 23, 42, 0.3)",
    },
    animationType: "shimmer",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 43,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "celestial-serpent",
    name: "Celestial Serpent",
    nameAr: "الأفعى الكونية الفلكية",
    description: "Cosmic Ouroboros serpent coiling through an indigo spiral galaxy with glowing constellation scales and infinite starlight rings.",
    descriptionAr: "أفعى الأوربوروس الكونية تلتف عبر مجرة حلزونية بلون النيلي مع حراشف من الأبراج النجمية وحلقات ضوء لا نهائية.",
    extendedDescription: "Encircling the outer rim of space, this cosmic serpent glows with stellar constellation nodes and swirling spiral arms that pulse with the rhythm of the cosmos.",
    extendedDescriptionAr: "تطوق الحافة الخارجية للفضاء الشاسع، تتوهج هذه الأفعى بعقد فلكية وأذرع حلزونية مجرية تنبض بإيقاع الكون الهادئ.",
    tags: ["mythical", "serpent", "cosmic", "galaxy", "legendary", "ouroboros"],
    category: "mythical",
    rarity: "legendary",
    badge: "Cosmic Ouroboros",
    badgeAr: "أفعى المجرات",
    colors: {
      primary: "#6366f1",
      secondary: "#312e81",
      accent: "#a855f7",
      glow: "rgba(99, 102, 241, 0.45)",
      particles: "#c7d2fe",
      overlay: "rgba(30, 27, 75, 0.35)",
    },
    animationType: "orbit",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 44,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "ember-phoenix",
    name: "Ember Phoenix",
    nameAr: "فينيق الجمرات المتوهجة",
    description: "Intensely glowing fledgling phoenix taking flight amidst swirling embers, volcanic updrafts, and blazing gold solar crown flares.",
    descriptionAr: "طائر فينيق متوهج بعنفوان ينطلق في الفضاء وسط دوامات الجمر الصاعد وتيارات الهواء البركاني وألسنة تاج شمسية ذهبية.",
    extendedDescription: "Rising like molten gold from the heart of a solar furnace, with soaring plumage of ruby and amber that leaves a brilliant trail of sparkling embers across the screen.",
    extendedDescriptionAr: "ينبثق كالذهب المنصهر من قلب الأفران الشمسية، بريش ياقوتي وكهرماني يترك خلفه أثرًا باهرًا من الجمرات المتلألئة المتصاعدة.",
    tags: ["mythical", "phoenix", "fire", "ember", "legendary", "solar"],
    category: "mythical",
    rarity: "legendary",
    badge: "Molten Crest",
    badgeAr: "شعلة الصهارة",
    colors: {
      primary: "#ea580c",
      secondary: "#7c2d12",
      accent: "#fbbf24",
      glow: "rgba(234, 88, 12, 0.45)",
      particles: "#fef08a",
      overlay: "rgba(67, 20, 7, 0.3)",
    },
    animationType: "pulse",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 45,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "stone-guardian",
    name: "Stone Guardian",
    nameAr: "حارس الحجر الروني القديم",
    description: "Ancient monolithic runic colossus with glowing cyan arcane glyphs etched across cracked granite plates and floating basalt debris.",
    descriptionAr: "عملاق روني متجانس قديم بنقوش سحرية سيانية محفورة فوق ألواح الجرانيت المشققة مع صخور بازلتية عائمة.",
    extendedDescription: "A primordial earth titan animated by ancient runic magic, featuring pulsing cyan hieroglyphs, floating stone fragments, and an impenetrable sense of stability.",
    extendedDescriptionAr: "عملاق أرضي أولي تحركه التعاويذ الرونية القديمة، بنقوش سيانية مشعة وصخور معلقة بانعدام الجاذبية تعطي إحساسًا بالثبات والصلابة.",
    tags: ["mythical", "guardian", "earth", "rune", "epic", "stone"],
    category: "mythical",
    rarity: "epic",
    badge: "Rune Golem",
    badgeAr: "غولم روني",
    colors: {
      primary: "#06b6d4",
      secondary: "#1e293b",
      accent: "#38bdf8",
      glow: "rgba(6, 182, 212, 0.4)",
      particles: "#94a3b8",
      overlay: "rgba(15, 23, 42, 0.3)",
    },
    animationType: "pulse",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 46,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "mystic-leviathan",
    name: "Mystic Leviathan",
    nameAr: "ليفياثان الأعماق السحرية",
    description: "Translucent abyssal phantom leviathan swimming through glowing bioluminescent sea kelp and ethereal tidal ripples.",
    descriptionAr: "كائن ليفياثان طيفي شفاف يسبح بوقار عبر غابات الأعشاب البحرية المضيئة وتموجات المد والجزر الأثيرية.",
    extendedDescription: "A gentle giant drifting through deep ocean trenches, illuminated by ethereal cyan caustics, floating marine photophores, and deep undulating pressure waves.",
    extendedDescriptionAr: "عملاق محيطي وديع يتهادى عبر خنادق المحيط السحيقة، مضاءً بانكسارات أشعة سيانية وفقاعات فسفورية وتموجات مائية آسرة.",
    tags: ["mythical", "leviathan", "ocean", "water", "legendary", "abyss"],
    category: "mythical",
    rarity: "legendary",
    badge: "Abyssal Phantom",
    badgeAr: "طيف الأعماق",
    colors: {
      primary: "#14b8a6",
      secondary: "#042f2e",
      accent: "#2dd4bf",
      glow: "rgba(20, 184, 166, 0.45)",
      particles: "#99f6e4",
      overlay: "rgba(4, 47, 46, 0.35)",
    },
    animationType: "wave",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 47,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },

  // ── DARK / FANTASY (36 to 40) ──
  {
    effectId: "abyss-beast",
    name: "Abyss Beast",
    nameAr: "وحش الفراغ السحيق",
    description: "Eldritch shadow predator from the deep void with multiple glowing violet ocular orbs, curling shadow tentacles, and dark matter distortion.",
    descriptionAr: "مفترس ظلال كوني من الفراغ السحيق بعيون جمشتية متعددة المتوهجة ومجسات ظل لولبية وتشوه في نسيج المادة المظلمة.",
    extendedDescription: "Dwelling in the space between dimensions, this shadowy titan bends background light into dark violet rings, surrounded by mysterious floating void anomalies.",
    extendedDescriptionAr: "يعيش في الفراغ بين الأبعاد، يحني هذا الكائن الضوء إلى حلقات بنفسجية داكنة محاطًا بظلال غامضة وتشوهات مادة مظلمة تمنح البروفايل طابعًا مهيبًا.",
    tags: ["dark", "void", "abyss", "eldritch", "legendary", "shadow"],
    category: "dark",
    rarity: "legendary",
    badge: "Eldritch Void",
    badgeAr: "فراغ كوني",
    colors: {
      primary: "#9333ea",
      secondary: "#3b0764",
      accent: "#c084fc",
      glow: "rgba(147, 51, 234, 0.45)",
      particles: "#e9d5ff",
      overlay: "rgba(24, 9, 44, 0.4)",
    },
    animationType: "wave",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 48,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "shadow-raven",
    name: "Shadow Raven",
    nameAr: "غراب الظلال الشبحية",
    description: "Spectral phantom raven dissolving into dark smoke wisps with glowing violet wing tips and an ethereal nocturnal aura.",
    descriptionAr: "غراب شبحي أثيري يتلاشى في خصلات دخان داكن مع أطراف أجنحة بنفسجية مشعة وهالة ليلية غامضة.",
    extendedDescription: "A messenger of the twilight realm that seamlessly weaves between physical form and dark smoke plumes, leaving glowing purple trails in its wake.",
    extendedDescriptionAr: "رسول عوالم الشفق الذي يتنقل بسلاسة بين الهيئة المادية والدخان الأثيري، تاركًا خلفه مسارات بنفسجية مشعة تتماوج بهدوء.",
    tags: ["dark", "raven", "spectral", "shadow", "epic", "phantom"],
    category: "dark",
    rarity: "epic",
    badge: "Phantom Wing",
    badgeAr: "جناح الشبح",
    colors: {
      primary: "#8b5cf6",
      secondary: "#1e1b4b",
      accent: "#a855f7",
      glow: "rgba(139, 92, 246, 0.4)",
      particles: "#ddd6fe",
      overlay: "rgba(15, 10, 35, 0.35)",
    },
    animationType: "drift",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 49,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "phantom-wolf",
    name: "Phantom Wolf",
    nameAr: "ذئب الأطياف المتلاشي",
    description: "Ghostly spectral wolf flickering between existence planes with translucent violet fur trails and spectral moonbeams.",
    descriptionAr: "ذئب شبحي أثيري يتردد بين عوالم الوجود مع ذيل من الفراء البنفسجي الشفاف ولمسات من ضوء القمر الأثيري.",
    extendedDescription: "Phasing silently across astral plains, the Phantom Wolf blurs the line between mist and beast, creating an ultra-clean, elusive presence on your profile.",
    extendedDescriptionAr: "ينتقل بصمت عبر العوالم الأثيرية، يدمج ذئب الأطياف بين الضباب والوحش ليخلق حضورًا بصريًا ساحرًا وفائق الأناقة على بروفايلك.",
    tags: ["dark", "wolf", "phantom", "spectral", "epic", "phase"],
    category: "dark",
    rarity: "epic",
    badge: "Phase Stalker",
    badgeAr: "مطارد الأطياف",
    colors: {
      primary: "#a855f7",
      secondary: "#2e1065",
      accent: "#c084fc",
      glow: "rgba(168, 85, 247, 0.4)",
      particles: "#f3e8ff",
      overlay: "rgba(15, 10, 35, 0.35)",
    },
    animationType: "drift",
    performanceTier: "medium",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 50,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "void-guardian",
    name: "Void Guardian",
    nameAr: "حارس هاوية الفضاء",
    description: "Armored sentinel of the cosmic abyss standing guard at the edge of the universe with a dark singularity shield and pulsing void energy.",
    descriptionAr: "حارس مدجج بدروع هاوية الفضاء يقف عند حافة الكون حاملاً درع تفرد أسود وطاقة فراغ نابضة.",
    extendedDescription: "A towering cosmic guardian clad in obsidian armor plate, shielding the realm from chaotic void storms while emitting a rhythmic, low-frequency gravitational hum.",
    extendedDescriptionAr: "حارس كوني مهيب يرتدي دروع الأوبسيديان الفضائية، يحمي الكون من عواصف الفراغ مشعًا بنبضات جاذبية منخفضة التردد فائقة الهيبة.",
    tags: ["dark", "guardian", "void", "sentinel", "legendary", "armor"],
    category: "dark",
    rarity: "legendary",
    badge: "Cosmic Sentinel",
    badgeAr: "حارس الأفق",
    colors: {
      primary: "#7c3aed",
      secondary: "#09090b",
      accent: "#ec4899",
      glow: "rgba(124, 58, 237, 0.45)",
      particles: "#f472b6",
      overlay: "rgba(9, 9, 11, 0.5)",
    },
    animationType: "pulse",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: false,
    isDefaultUnlocked: true,
    displayOrder: 51,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
  {
    effectId: "eclipse-dragon",
    name: "Eclipse Dragon",
    nameAr: "تنين كسوف الشمس الكوني",
    description: "Colossal dragon silhouette eclipsing a brilliant dying star, with golden corona rim light flaring along obsidian dragon wings and dark stellar winds.",
    descriptionAr: "تنين كوني عملاق يكسف نجمًا وهاجًا مع هالة شمسية ذهبية تلتهب على حواف أجنحة الأوبسيديان ورياح نجمية مظلمة.",
    extendedDescription: "The ultimate cosmic eclipse incarnate: an immense dragon wingspan masking a blazing solar core, producing a blinding golden corona outline against pure deep void black.",
    extendedDescriptionAr: "التجسيد الأسمى للكسوف الكوني: أجنحة تنين عملاقة تحجب قلب الشمس الملتهب، لتنتج هالة ذهبية إشعاعية مذهلة تضيء حواف الأجنحة فوق سواد الفضاء السحيق.",
    tags: ["dark", "dragon", "eclipse", "corona", "legendary", "gold"],
    category: "dark",
    rarity: "legendary",
    badge: "Solar Corona",
    badgeAr: "كسوف التنين",
    colors: {
      primary: "#f59e0b",
      secondary: "#09090b",
      accent: "#fbbf24",
      glow: "rgba(245, 158, 11, 0.5)",
      particles: "#fef08a",
      overlay: "rgba(9, 9, 11, 0.55)",
    },
    animationType: "pulse",
    performanceTier: "high",
    isAnimated: true,
    isActive: true,
    isFeatured: true,
    isDefaultUnlocked: true,
    displayOrder: 52,
    layersConfig: { baseBackground: true, ambientGradient: true, lightGlow: true, particles: true, atmosphericMesh: true, interactivePointer: true, vignetteOverlay: true },
  },
];

// Helper to seed/synchronize effects in database
export async function ensureEffectsSeeded() {
  try {
    for (const item of INITIAL_EFFECTS) {
      await (ProfileEffect as any).findOneAndUpdate(
        { effectId: item.effectId },
        { $setOnInsert: item },
        { upsert: true, new: true }
      );
    }
  } catch (err) {
    logger.warn({ err }, "Could not seed effects to database (DB might be offline)");
  }
}

// ── GET /api/profile/effects ──────────────────────────────────────────────────
router.get("/profile/effects", optionalAuth, async (req: AuthRequest, res): Promise<void> => {
  try {
    let effects: any[] = [];
    try {
      effects = await (ProfileEffect as any).find({ isActive: true }).sort({ displayOrder: 1 }).lean();
    } catch {
      effects = INITIAL_EFFECTS.filter(e => e.isActive);
    }

    if (!effects || effects.length === 0) {
      effects = INITIAL_EFFECTS.filter(e => e.isActive);
    }

    // Determine user status
    let userUnlockedIds: string[] = [];
    let userActiveId: string | null = null;

    if (req.userId) {
      try {
        const user = await User.findById(req.userId).select("activeProfileEffectId unlockedProfileEffects subscriptionPlan role");
        if (user) {
          userActiveId = user.activeProfileEffectId || null;
          userUnlockedIds = user.unlockedProfileEffects || [];
        }
      } catch {
        // Ignore user lookup error
      }
    }

    const category = typeof req.query.category === "string" ? req.query.category : undefined;
    let filtered = effects;
    if (category && category !== "all") {
      filtered = filtered.filter(e => e.category === category);
    }

    const result = filtered.map(e => {
      const isOwned = e.isDefaultUnlocked || userUnlockedIds.includes(e.effectId);
      const isSelected = userActiveId === e.effectId;
      return {
        id: e.effectId,
        effectId: e.effectId,
        name: e.name,
        nameAr: e.nameAr || e.name,
        description: e.description,
        descriptionAr: e.descriptionAr || e.description,
        category: e.category,
        rarity: e.rarity,
        badge: e.badge || null,
        badgeAr: e.badgeAr || null,
        colors: e.colors,
        animationType: e.animationType,
        performanceTier: e.performanceTier,
        isAnimated: e.isAnimated,
        isFeatured: e.isFeatured,
        isDefaultUnlocked: e.isDefaultUnlocked,
        layersConfig: e.layersConfig,
        isOwned,
        isSelected,
        status: isSelected ? "selected" : (isOwned ? "owned" : "locked"),
      };
    });

    res.json({
      effects: result,
      activeProfileEffectId: userActiveId,
      total: result.length,
    });
  } catch (err: any) {
    logger.error({ err }, "Failed to get profile effects");
    res.status(500).json({ error: "Failed to retrieve profile effects" });
  }
});

// ── GET /api/profile/effects/:id ──────────────────────────────────────────────
router.get("/profile/effects/:id", optionalAuth, async (req: AuthRequest, res): Promise<void> => {
  const { id } = req.params;
  try {
    let effect = await (ProfileEffect as any).findOne({ effectId: id }).lean();
    if (!effect) {
      effect = INITIAL_EFFECTS.find(e => e.effectId === id) as any;
    }

    if (!effect || !effect.isActive) {
      res.status(404).json({ error: "Profile effect not found or currently unavailable" });
      return;
    }

    let isOwned = effect.isDefaultUnlocked;
    let isSelected = false;

    if (req.userId) {
      const user = await User.findById(req.userId).select("activeProfileEffectId unlockedProfileEffects");
      if (user) {
        if (user.unlockedProfileEffects?.includes(effect.effectId)) isOwned = true;
        if (user.activeProfileEffectId === effect.effectId) isSelected = true;
      }
    }

    res.json({
      ...effect,
      id: effect.effectId,
      isOwned,
      isSelected,
    });
  } catch (err: any) {
    res.status(500).json({ error: "Failed to fetch effect details" });
  }
});

// ── POST /api/profile/effects/:id/apply ───────────────────────────────────────
router.post("/profile/effects/:id/apply", requireAuth, async (req: AuthRequest, res): Promise<void> => {
  const { id } = req.params;

  try {
    const user = await User.findById(req.userId);
    if (!user) {
      res.status(404).json({ error: "User not found" });
      return;
    }

    let effect = await (ProfileEffect as any).findOne({ effectId: id, isActive: true });
    if (!effect) {
      const memoryMatch = INITIAL_EFFECTS.find(e => e.effectId === id && e.isActive);
      if (!memoryMatch) {
        res.status(404).json({ error: "Profile effect not found or unavailable" });
        return;
      }
      effect = memoryMatch as any;
    }

    const isDefaultUnlocked = effect.isDefaultUnlocked;
    const isUserOwned = user.unlockedProfileEffects?.includes(effect.effectId);
    const isVipOrAdmin = user.role === "admin" || user.role === "superadmin" || user.subscriptionPlan === "vip" || user.subscriptionPlan === "business";

    if (!isDefaultUnlocked && !isUserOwned && !isVipOrAdmin) {
      res.status(403).json({
        error: "This effect is locked. Upgrade your subscription or unlock it to apply.",
      });
      return;
    }

    user.activeProfileEffectId = effect.effectId;
    await user.save();

    res.json({
      message: `Applied ${effect.name} profile effect!`,
      activeProfileEffectId: user.activeProfileEffectId,
      effect,
    });
  } catch (err: any) {
    logger.error({ err }, "Apply profile effect error");
    res.status(500).json({ error: "Failed to apply profile effect" });
  }
});

// ── DELETE /api/profile/effects/active ────────────────────────────────────────
router.delete("/profile/effects/active", requireAuth, async (req: AuthRequest, res): Promise<void> => {
  try {
    const user = await User.findByIdAndUpdate(
      req.userId,
      { activeProfileEffectId: null },
      { new: true }
    );

    if (!user) {
      res.status(404).json({ error: "User not found" });
      return;
    }

    res.json({
      message: "Active profile effect removed successfully",
      activeProfileEffectId: null,
    });
  } catch (err: any) {
    res.status(500).json({ error: "Failed to remove active profile effect" });
  }
});

export default router;
