import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import postsRouter from "./posts";
import storiesRouter from "./stories";
import notificationsRouter from "./notifications";
import messagesRouter from "./messages";
import groupsRouter from "./groups";
import exploreRouter from "./explore";
import reelsRouter from "./reels";
import aiRouter from "./ai";
import vaultRouter from "./vault";
import closeFriendsRouter from "./close-friends";
import pushRouter from "./push";
import notesRouter from "./notes";
import linkPreviewRouter from "./link-preview";
import reportsRouter from "./reports";
import pollsRouter from "./polls";
import gamesRouter from "./games";
import settingsRouter from "./settings";
import gifsRouter from "./gifs";
import spotifyRouter from "./spotify";
import feedbackRouter from "./feedback";
import seoRouter from "./seo";
import institutionalRouter from "./institutional";
import verificationRouter from "./verification";
import plansRouter from "./plans";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use("/admin", adminRouter);
router.use(verificationRouter);
router.use(plansRouter);
router.use(healthRouter);
router.use(seoRouter);
router.use(institutionalRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(settingsRouter);
router.use(gifsRouter);
router.use(spotifyRouter);
router.use(feedbackRouter);
router.use(postsRouter);
router.use(storiesRouter);
router.use(notificationsRouter);
router.use(messagesRouter);
router.use(groupsRouter);
router.use(exploreRouter);
router.use(reelsRouter);
router.use(aiRouter);
router.use(vaultRouter);
router.use(closeFriendsRouter);
router.use(pushRouter);
router.use(notesRouter);
router.use(linkPreviewRouter);
router.use(reportsRouter);
router.use(pollsRouter);
router.use(gamesRouter);

export default router;
